### ISSUE TITLE
[react-native-payments] install via npm fails

### ISSUE THREAD

**Issue by LYevhen** [rnw-community/rnw-community#176] opened 2024-01-25 14:10 UTC
Hey, I'm having an issue during installation of package via npm
node -v
v21.5.0

npm -v
10.2.4

npm install @rnw-community/react-native-payments
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

**Comment by vitalyiegorov** [comment] 2024-02-07 07:12
This is due to using the yarn workspace protocol inside the monorepo of this project, I will double check why it was not replaced during the publication to NPM

**Comment by vitalyiegorov** [comment] 2024-02-07 07:48
@LYevhen please confirm that the `@rnw-community/react-native-payments0.65.5` version is working and reopen if needed.

**Comment by LYevhen** [comment] 2024-02-07 10:23
@vitalyiegorov, I can confirm that module now installs via npm but now it throws an error in loop
![image](https://github.com/rnw-community/rnw-community/assets/44976185/6494f1c9-fe4b-4082-a4fa-abc6f441449c)

And it seems that with yarn it is broken as-well, revert back to 0.65.4 fix issue for yarn but looks like library is broken for 0.65.5

**Comment by vitalyiegorov** [comment] 2024-02-07 15:48
Please try the [`react-native-payments-example` ](https://github.com/rnw-community/rnw-community/tree/master/packages/react-native-payments-example) project from this repo, just checked and it works perfectly on the iPhone simulator

**Comment by LYevhen** [comment] 2024-02-08 14:44
@vitalyiegorov, My apologies, forgot to mention ( real device, or simulator, does not matter )
Steps to repro
v0.65.4 - can not install via npm, can install with yarn, both platforms works, debug and not debug mode (android, iOS)

v0.65.5 - can install via npm, can install with yarn, iOS, android works, but it does not work in debug mode, throws an errors in debug mode in console as shown on screenshot above, do not know if it will impact production

Have no idea why.

**Comment by vitalyiegorov** [comment] 2024-02-11 05:53
What version of the react-native are you using? @LYevhen

**Comment by LYevhen** [comment] 2024-02-13 10:22
@vitalyiegorov,
I have 0.71.15, tried with "react-native": "^0.72.3", which is in PR in 0.65.5, same behaviour on both.

**Comment by vitalyiegorov** [comment] 2024-02-18 06:43
Can you please create a reproducible repository so I can help?

**Comment by oleksii-burachyk** [comment] 2024-04-24 20:12
Hi @LYevhen, have you figured it out? I have the same issue atm.
Thanks in advance

> @vitalyiegorov, I can confirm that module now installs via npm but now it throws an error in loop ![image](https://private-user-images.githubusercontent.com/44976185/302944833-6494f1c9-fe4b-4082-a4fa-abc6f441449c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODk3NjQsIm5iZiI6MTcxMzk4OTQ2NCwicGF0aCI6Ii80NDk3NjE4NS8zMDI5NDQ4MzMtNjQ5NGYxYzktZmU0Yi00MDgyLWE0ZmEtYWJjNmY0NDE0NDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDIwMTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNTJlMWNlNDI3YjEwNzc3OGM0YTI3YjFkOWI4OWZjZTBlZWUyZjRmMjU4YWQzMGJiNmEyNjBlZjUyYzRhODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.157qsvgwaD5-iu_ntzoIsst8tmYNMV4O8l0nz-aD7Xw)
> 
> And it seems that with yarn it is broken as-well, revert back to 0.65.4 fix issue for yarn but looks like library is broken for 0.65.5

**Comment by vitalyiegorov** [comment] 2024-05-19 07:54
@oleksii-burachyk @LYevhen Can we close this issue or it is still valid?

**Closed** 2024-06-03 04:53 UTC
